# Generated by Django 2.2.1 on 2019-06-06 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_person_doc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='doc',
        ),
        migrations.DeleteModel(
            name='Documento',
        ),
    ]
