# Generated by Django 2.2.1 on 2019-06-09 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0007_produto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Produto',
        ),
    ]
