# Generated by Django 2.2.1 on 2019-06-19 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0013_auto_20190619_1445'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IntensDoPedido',
            new_name='ItensDoPedido',
        ),
    ]
