# Generated by Django 2.2.1 on 2019-06-21 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0014_auto_20190619_1448'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venda',
            name='pessoa',
        ),
        migrations.DeleteModel(
            name='ItensDoPedido',
        ),
        migrations.DeleteModel(
            name='Produto',
        ),
        migrations.DeleteModel(
            name='Venda',
        ),
    ]
