# Generated by Django 2.2.1 on 2019-12-12 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0017_auto_20191212_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='user_images')),
            ],
        ),
        migrations.AlterField(
            model_name='person',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.Image'),
        ),
    ]
