# Generated by Django 2.2.1 on 2019-12-12 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0020_auto_20191212_2030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='photo',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
